### ISSUE TITLE
Re-pairing

### ISSUE THREAD

**Issue by ajcb69** [Koenkk/zigbee2mqtt.io#1]
Raspberry 3b+ home assistant. 
I had to format sd and reinstall ha because don´t run.
When I install zigbee2mqtt, i have restored the data directory with a backup stored.
Now in Home assistant  recognize the entities but don´t record any activity from sensors  when p.e. a door is opened or closed.
![sensors](https://user-images.githubusercontent.com/45384079/52714009-1fb57c00-2f99-11e9-8aa7-715f0ee22188.jpg)
 I can see the old zigbbe map but not update
![map](https://user-images.githubusercontent.com/45384079/52714111-6014fa00-2f99-11e9-8ffe-f85847ae4b78.jpg)

It´s possible to repair or i have to rejoin all sensors?
Thank you and excuse me for my bad english

**Comment by Koenkk** [comment]
This is the issue tracker for the documentation, please open an issue here: https://github.com/Koenkk/zigbee2mqtt/issues
