### ISSUE TITLE
Instructions to test locally

### ISSUE THREAD

**Issue by KapJI** [Koenkk/zigbee2mqtt.io#11]
It would be helpful if you add instructions how to run local Jekyll instance for testing changes locally.
I think for this you need to check in Gemfile and write instructions how to install bundler, jekyll and cayman theme.

**Comment by Koenkk** [comment]
To be honest, I never did this.

**Comment by KapJI** [comment]
Well, as you can see on example with tables Jekyll renders Markdown slightly differently from github preview. Jekyll requires empty lines before tables when github is fine with anything which is non paragraph. Local testing allows to see how final page will look like and avoid such situations when all tables of the page are broken.

**Comment by Koenkk** [comment]
Added the instructions, thanks.
