### ISSUE TITLE
MQTT payload questions

### ISSUE THREAD

**Issue by goldriver2** [Koenkk/zigbee2mqtt.io#12]
I am working at integrating a Stelpro baseboard thermostat in zigbe2mqtt, so far I have been able to pair the device. I figured out the FromZigee an To Zigbee and I have been able to see payload from the thermostat in my MQTT server

The question I now have, I tought that defining the _**(cb) => device.report**_ would create the payload that would be sent out to my MQTT but actually I only have ::
(cb) => device.report('hvacThermostat', 'localTemp', 300, 3600, 0, cb),
(cb) => device.report('hvacThermostat', 'occupiedHeatingSetpoint', 1, 0, 1, cb),

defined in my device.js but I have a Payload like::

{"local_temperature":23,"linkquality":28,"occupied_heating_setpoint":24,"pi_heating_demand":0}

Where does the linkquality and pl_heating_demand are coming from ?

**Comment by Koenkk** [comment]
This is the documentation issue tracker, please open this issue at https://github.com/koenkk/zigbee2mqtt/issues
