### ISSUE TITLE
Failed to mount the cieApp

### ISSUE THREAD

**Issue by Fabiancrg** [Koenkk/zigbee2mqtt.io#13]
Hi,
Today I built a coordinator with a CC2530 and ESP8266, it seems to be working but I have joined only one Xiaomi so far.
I just have an error and I don't know what it means.
When the I start zigbee2mqtt, I get this in the log:
fabian@NUC:/opt/zigbee2mqtt/data/log/2019-02-19.18-40-40$ cat log.txt
2/19/2019, 6:40:40 PM - info: Logging to directory: '/opt/zigbee2mqtt/data/log/2019-02-19.18-40-40'
2/19/2019, 6:40:40 PM - info: Starting zigbee2mqtt version 1.1.1 (commit #92d88b6)
2/19/2019, 6:40:40 PM - info: Starting zigbee-shepherd
2/19/2019, 6:40:40 PM - info: Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
2/19/2019, 6:41:40 PM - info: Starting zigbee-shepherd
2/19/2019, 6:41:43 PM - info: zigbee-shepherd started
2/19/2019, 6:41:43 PM - info: Coordinator firmware version: '20190109'
2/19/2019, 6:41:43 PM - info: Currently 1 devices are joined:
2/19/2019, 6:41:43 PM - info: 0x00158d0001bb322d (0x00158d0001bb322d): SJCGQ11LM - Xiaomi Aqara water leak sensor (EndDevice)
2/19/2019, 6:41:43 PM - info: Zigbee: disabling joining new devices.
2/19/2019, 6:41:43 PM - info: Connecting to MQTT server at mqtt://localhost:1883
2/19/2019, 6:41:43 PM - info: zigbee-shepherd ready
2/19/2019, 6:41:43 PM - info: Connected to MQTT server
2/19/2019, 6:41:43 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
2/19/2019, 6:41:43 PM - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0001bb322d', payload '{"battery":100,"voltage":3005,"linkquality":78}'
2/19/2019, 6:41:46 PM - error: Failed to mount the cieApp
2/19/2019, 6:42:46 PM - info: Zigbee: allowing new devices to join.
2/19/2019, 6:42:46 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","permit_join":true}'

zigbee2mqtt seems ok but does the error "Failed to mount the cieApp" means ?

Thank you,
Fabian

**Comment by Koenkk** [comment]
This is the zigbee2mqt documentation issue tracker please open the issue here: https://github.com/Koenkk/zigbee2mqtt/issues
