### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by bochelork** [Koenkk/zigbee2mqtt.io#18]
the page
https://www.zigbee2mqtt.io/information/supported_devices.html
links to:
https://github.com/Koenkk/zigbee2mqtt/blob/dev/docs/getting_started/pairing_devices.md
which is not available.

Thanks.

**Comment by pixeldoc2000** [comment]
I can't find a broken link on this page. There is only one link to [https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html) which is ok.

Screenshot?

**Comment by Koenkk** [comment]
fixed, thanks!
