### ISSUE TITLE
CC2531 ad router 

### ISSUE THREAD

**Issue by h4nc** [Koenkk/zigbee2mqtt.io#2]
I already know that you have to reflash a CC2530 if you have to repair it. It has no buttons to perform a reset.

Does a CC2531 flashes as a router have the ability to be reset, or do we also have to reflash it?

PS: what’s the reason why you switched to zigbee2mqtt.io ?

**Comment by Koenkk** [comment]
This is the zigbee2mqtt documentation tracker, please open an issue here: https://github.com/Koenkk/zigbee2mqtt/issues
