### ISSUE TITLE
How to round values sent to MQTT?

### ISSUE THREAD

**Issue by wsw70** [Koenkk/zigbee2mqtt.io#24]
**Is it possible to round the values sent to MQTT?** 

I am currently seeing temperatures such as 21.37°C which is way to precise for me (21°C) would be enough. I suspect that the 0.37°C is not relevant anyway in terms of accuracy.

**Comment by Koenkk** [comment]
see http://www.zigbee2mqtt.io/configuration/device_specific_configuration.html

**Comment by wsw70** [comment]
Thank you - `device_options` worked beautifully
