### ISSUE TITLE
Connecting devices to router

### ISSUE THREAD

**Issue by KoumaMisna** [Koenkk/zigbee2mqtt.io#25]
I flashed another CC-stick with router firmware and was able to pair it with the coordinator. Also I deleted coordinators database so it has no devices connected.

Now if I try to pair for example Xiaomi Aqara temperature sensors they all pair to the coordinator even though the router is 5cm from the device and coordinator is on another floor.
And how can I tell this, well the end device reports link quality between 7 and 0.

So my question is that how am I able to select to which device I want to pair the end devices?

**Comment by Koenkk** [comment]
Please open this issue on the zigbee2mqtt repo, this is the documentation repo.
