### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by joseluisgodinho** [Koenkk/zigbee2mqtt.io#31]
Hello

Is there any forum were the community could answer to each other?

I find this na excellent project but its to closed, and  we need to start sharing user experience

I for exemple have 16 devices connected and have huge issues  with the GLEDOPTO and Ikea lamps.

thank you for you work
JLG

**Comment by Koenkk** [comment]
That would be nice, do you have any idea which services could be used for this?

**Comment by joseluisgodinho** [comment]
I like very much the one that nodered usues 
https://www.discourse.org/ albeit we could use a googles group

**Comment by Koenkk** [comment]
Nice, I see that discourse has some options for free hosting (https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/). Will try to get into contact with them.

**Comment by Tontze** [comment]
How about discord channel ? Home assistant has channel there, so does esphome, tasmota too

**Comment by Koenkk** [comment]
Discord channel is live: https://github.com/Koenkk/zigbee2mqtt/blob/master/README.md

**Comment by Koenkk** [comment]
Forum is online! Link are available on http://www.zigbee2mqtt.io/
