### ISSUE TITLE
Cant start npm

### ISSUE THREAD

**Issue by shafiq786110** [Koenkk/zigbee2mqtt.io#5]
Im very new to linux but im trying to set up the zigbee2MQTT plugin

I am following the steps as here: https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html

I get upto the "npm start" command and get this output: 

pi@raspberrypi:/opt/zigbee2mqtt $ npm start

> zigbee2mqtt@1.1.1 start /opt/zigbee2mqtt
> node index.js

/opt/zigbee2mqtt/node_modules/js-yaml/lib/js-yaml/loader.js:171
  throw generateError(state, message);
  ^
YAMLException: bad indentation of a mapping entry at line 14, column 4:
       user: username
       ^
    at generateError (/opt/zigbee2mqtt/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/opt/zigbee2mqtt/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readBlockMapping (/opt/zigbee2mqtt/node_modules/js-yaml/lib/js-yaml/loader.js:1080:7)
    at composeNode (/opt/zigbee2mqtt/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockMapping (/opt/zigbee2mqtt/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/opt/zigbee2mqtt/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/opt/zigbee2mqtt/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/opt/zigbee2mqtt/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (/opt/zigbee2mqtt/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Object.safeLoad (/opt/zigbee2mqtt/node_modules/js-yaml/lib/js-yaml/loader.js:1591:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.1.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-02-14T00_43_05_407Z-debug.log

Im not sure what to do next, im currently triallingi this on a raspberry pi, with the usb adapter plugged in.

My username for mosquitto is "username" and its running on the same pi 

All the steps before this have worked fine and i have mosquitto running ok too. 

Please help! Im so close to getting this working (i hope), but im pulling my hair out now with my very limited knowledge

Thanks :)

**Comment by shafiq786110** [comment]
This is a copy of the debug file that it refers to: 

0 info it worked if it ends with ok
1 verbose cli [ '/opt/nodejs/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.1.1~prestart: zigbee2mqtt@1.1.1
6 info lifecycle zigbee2mqtt@1.1.1~start: zigbee2mqtt@1.1.1
7 verbose lifecycle zigbee2mqtt@1.1.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.1.1~start: PATH: /opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/zigbee2mqtt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle zigbee2mqtt@1.1.1~start: CWD: /opt/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.1.1~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.1.1~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.1.1~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.1.1 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid zigbee2mqtt@1.1.1
15 verbose cwd /opt/zigbee2mqtt
16 verbose Linux 4.14.79-v7+
17 verbose argv "/opt/nodejs/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.1.1 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.1.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Koenkk** [comment]
This is the zigbee2mqtt documentation tracker, please open an issue here: https://github.com/Koenkk/zigbee2mqtt/issues

You probably have a syntax error in your `configuration.yaml`.
