### ISSUE TITLE
RTCGQ11LM sensor don't return battery

### ISSUE THREAD

**Issue by goldriver2** [Koenkk/zigbee2mqtt.io#53]
I installed this device and it has been running for 3 days and it only reports:

zigbee2mqtt:info 2019-3-20 06:00:35 MQTT publish: topic 'zigbee2mqtt/Detecteur mouvement', payload '{"illuminance":186,"linkquality":15,"occupancy":true}'

I saw in many other post that their devices were reporting the following:

2018-08-15T07:36:27.539Z - info: MQTT publish, topic: 'zigbee2mqtt/0x00158d0002006aa6', payload: '{"illuminance":122,"occupancy":false,"battery":"100.00","voltage":3005}'

What could be the difference from my configuration so that I don't have the battery and voltage reported ?

**Comment by Koenkk** [comment]
Could you try re-pairing the device and keeping it closer to the coordinator? (it's really strange that it doesn't report it, even after 3 days).

**Comment by goldriver2** [comment]
This time it seems to be working, strange everything seemed fine the first time !
Thanks
