### ISSUE TITLE
Xiaomi RTCGQ01LM not recognized at docker installation

### ISSUE THREAD

**Issue by jgyoldi** [Koenkk/zigbee2mqtt.io#54]
Hello,

I am migrating my HA installation from a RPI with Raspbian to a NUC with Debian 9 and Docker. I have installed successfully HA in a container, mqttt in another and I am trying to run zigbee2mqtt in another one. The container runs properly but when I pair a device, the following message appears in the log:
___________________________
zigbee2mqtt:warn 3/21/2019, 8:46:10 PM No converter available for 'RTCGQ01LM' with cid 'msOccupancySensing', type 'attReport' and data '{"cid":"msOccupancySensing","data":{"occupancy":1}}'

  zigbee2mqtt:warn 3/21/2019, 8:46:10 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
__________________________________

I made the installation following your web guide.

Where can be the error?

Regards,

Jose

**Comment by Koenkk** [comment]
can you provide your docker run command?

**Comment by jgyoldi** [comment]
I have created a working dir at "/docker/zigbee2mqtt/", copied all my raspberry pi data dir to "/docker/zigbee2mqtt/data" and lib dir from you latest github repository of zigbee2mqtt-master to "/docker/zigbee2mqtt/lib". Then executed:

$ git clone https://github.com/Koenkk/zigbee-shepherd-converters.git /docker/zigbee2mqtt/data/zigbee-shepherd-converters

$ sudo chown -R myuser:myuser /docker/zigbee2mqtt

And finallly the docker with the following command:

$ docker run \
   -it \
   --name="zigbee2mqtt" \
   --restart unless-stopped \
   -v /docker/zigbee2mqtt/data:/app/data \
   -v /docker/zigbee2mqtt/data/zigbee-shepherd-converters:/app/node_modules/zigbee-shepherd-converters \
   -v /docker/zigbee2mqtt/lib:/app/lib \
   --device=/dev/ttyACM0 \
   koenkk/zigbee2mqtt

Everythings seems to go right: recognizes the hardware, the configuration.yaml, mqtt, mqtt commands and sensors at homeassistant but when I start pairing my devices, it doesn't recognize the xiaomi RTCGQ01LM.

**Comment by Koenkk** [comment]
@jgyoldi you should use this docker command: http://www.zigbee2mqtt.io/information/docker.html#amd64

(the one you used should be used when supporting new devices).

**Comment by jgyoldi** [comment]
Thanks!!! It works fine with it. I misunderstood the guide, I thought it was necessary the other for HA.
